### ISSUE TITLE
Browser in php-fpm Docker times out and never fetches data (default LoopInterface implementation)

### ISSUE THREAD

**Issue by meglio** [clue/reactphp-buzz#112]
Prerequisites:

- The script is run in a php-fpm Docker container
- The command is wrapped in an instance of `Symfony\Component\Console\Command\Command`
- Host machine MacOS latest

Test:

```php
$loop = React\EventLoop\Factory::create();

$loop->addTimer(11, function()use($loop) {
            echo "Timed out\n";
            $loop->stop();
        });

$browser = new Browser($loop);

            /** @var Promise $promise */
            $promise = $browser->get('http://ukr.net/');
            $promise->done(
                function(Response $data){
                    echo 'Fulfilment code =: ' . $data->getCode();
                },
                function($reason) {
                    echo 'Rejection reason: ' . (string)$reason;
                }
            );

$loop->run();

```

Please note that requesting the same URL through php curl OR curl in console works just fine.

The result is always a `Timed out` output.

Am I doing something wrong? If not, where do I start to dig to find out what the issue is?

**Comment by clue** [comment]
Are you using the latest version? It looks like your resolver function will not be called due to the unknown `Response` type hint. The `then()` method will return a rejected promise in this case, you can chain this with an empty `->done()` call to report any issues in your chain.

It also looks like you may want to cancel the timer once the response is done. Currently, it will print the "timed out" message irrespective of whether the response resolved or rejected. See also #1.

I hope this helps :+1:
