### ISSUE TITLE
Using done() on request returns a null value

### ISSUE THREAD

**Issue by ace411** [clue/reactphp-buzz#118]
Hello, I recently started using your library within the context of an application powered by ReactPHP. I encountered a problem with the promises returned from the calls made via the client. 

```php
...
//function body
$client = new Browser($loop);

$request = $client->get(url, headers)->done(function ($response) {
  return (string) $response->getBody();
});

return $request;
...
```
The snippet of code above is a small part of a larger application. The problem I am encountering is that the request returns a null value and yet using the echo directive on the response prints a valid API response. I would like to know how to fix this.

**Comment by clue** [comment]
Hi @ace411, welcome to ReactPHP! :tada: 

It looks like you want to use `then()` instead of `done()` and your code should work :+1: 

Let's break this down:

```php
// broken
$request = $client->get(url, headers)->done(function ($response) {
  return (string) $response->getBody();
});
```

This is equivalent to this:

```php
// still broken
$promise = $client->get(url, headers);
$request = $promise->done(function ($response) {
  return (string) $response->getBody();
});
```

The `Promise::done()` method is documented to return `void`, hence why this example will return a `null` value here.

I hope this helps :+1:
