### ISSUE TITLE
Allow other PSR7 abstraction

### ISSUE THREAD

**Issue by Th3Mouk** [clue/reactphp-buzz#132]
Hello !

Thanks for this very usefull lib. 
While I tried to integrate it in my projects, I was wondering why you choose ringcentral instead of guzzle psr7 implementation.

I move beyond that, and now my question is why don't let the developper choose its own implementation [like in Buzz](https://github.com/kriswallsmith/Buzz/blob/master/lib/Browser.php). Because it was the lib that inspired this one.

If you're agree, I can help you to make this move. I'm currently working on an adaption of this lib, to provide some sugar with Reactive Programming operators. The outcome of this discussion may lead to more or less work for the adaptation.

Thanks for your time

**Comment by clue** [comment]
@Th3Mouk Happy to hear this project is useful to you!

This project is documented to use PSR-7 interfaces, the actual PSR-7 implementation is an implementation detail that really shouldn't matter for the most part. Accordingly, this implementation may also change over time and it is intentionally not covered in the documentation.

We're currently using `ringcentral/psr7` because it's a relatively lightweight PSR-7 implementation that happens to to support all PHP versions this project currently supports. Other than that, I really don't care much about this implementation either.

If there are some good reasons to change this implementation, then I'm not opposed to this change. As far as I'm concerned, I'm not aware of anything that is missing from the current implementation. If you feel like filing a PR, go for it and I'm happy to take a look and review this. However, keep in mind that I very much care about maintainability and long term support, so I aim to avoid adding unneeded complexity and instead like to focus on adding new features for consumers of this package.

I believe this has been answered, so I'm closing this for now. Please come back with more details if this persists and we can reopen this :+1:

**Comment by Th3Mouk** [comment]
Thank you for responding so fully. I understand your commitment, I'm just taking care of my dependencies and I try to avoid as much as I can useless one. I'm agree `ringcentral/psr7` is totally fine but my approach was to totally decouple the lib like [httplug](http://httplug.io/) recommendation. No need to reopen the issue now I have the background of the project, and features take precedence over optimisations.
